"""
ElevenLabs TTS Provider — eleven_v3 model.

Supports 70+ languages including 12 Indian languages.
Auto-detects language from text content — no language_code needed.

Expressive controls (all tuned per NarrativeBranch):

  stability  — 0.0 Creative / 0.5 Natural / 1.0 Robust
  style      — 0.0-1.0, amplifies speaker's expressiveness
  speed      — 0.7-1.2, slows dramatic moments, quickens death overs

Audio Tags (v3 feature):
  Bracketed cues like [excited], [gasps], [shouts] that the v3 model
  interprets as performance instructions for expressive delivery.
  Generated by the LLM directly in the commentary text when
  the TTS provider is ElevenLabs (see prompts.py).

Text formatting:
  v3 responds to ALL CAPS for emphasis, ellipses (…) for pauses,
  and dashes (—) for breaks. The LLM prompt encourages these.
"""

import logging

import httpx

from app.config import settings
from app.models import NarrativeBranch

logger = logging.getLogger(__name__)

ELEVENLABS_TTS_URL = "https://api.elevenlabs.io/v1/text-to-speech/{voice_id}"

# ------------------------------------------------------------------ #
#  Per-branch voice tuning
# ------------------------------------------------------------------ #
#  Each branch maps to (stability, style, speed):
#    stability — lower = more emotional range
#    style     — higher = more exaggerated delivery
#    speed     — <1.0 slows for gravity, >1.0 quickens for urgency

_VOICE_PROFILE: dict[NarrativeBranch, tuple[float, float, float]] = {
    # (stability, style, speed)
    NarrativeBranch.WICKET_DRAMA:       (0.0, 0.7, 0.85),   # max emotion, slow for drama
    NarrativeBranch.BOUNDARY_MOMENTUM:  (0.0, 0.5, 1.0),    # expressive, normal pace
    NarrativeBranch.EXTRA_GIFT:         (0.0, 0.4, 1.0),    # surprised energy
    NarrativeBranch.PRESSURE_BUILDER:   (0.5, 0.3, 0.9),    # tense, slightly slow
    NarrativeBranch.OVER_TRANSITION:    (0.5, 0.2, 1.0),    # balanced, analytical
    NarrativeBranch.ROUTINE:            (1.0, 0.0, 1.0),    # stable, no style boost
}

_DEFAULT_PROFILE = (0.5, 0.2, 1.0)
_PIVOT_PROFILE = (0.0, 0.6, 0.85)  # pivots always get dramatic treatment


def _get_voice_profile(
    branch: NarrativeBranch, is_pivot: bool
) -> tuple[float, float, float]:
    """Return (stability, style, speed) for the given narrative context."""
    if is_pivot:
        return _PIVOT_PROFILE
    return _VOICE_PROFILE.get(branch, _DEFAULT_PROFILE)


async def synthesize(
    text: str,
    branch: NarrativeBranch,
    is_pivot: bool = False,
    language: str = "en",
    voice_id: str = "",
    model_id: str = "",
) -> bytes | None:
    """
    Convert commentary text to speech using ElevenLabs API.
    Returns raw MP3 audio bytes, or None if TTS fails.

    Args:
        voice_id: ElevenLabs voice ID (from languages.json tts_voice_id).
        model_id: ElevenLabs model name (from languages.json tts_model).
    """
    if not settings.elevenlabs_api_key:
        logger.warning("ElevenLabs API key not configured, skipping TTS")
        return None

    stability, style, speed = _get_voice_profile(branch, is_pivot)
    voice_id = voice_id or settings.elevenlabs_voice_id
    model_id = model_id or "eleven_v3"

    url = ELEVENLABS_TTS_URL.format(voice_id=voice_id)

    payload: dict = {
        "text": text,
        "model_id": model_id,
        "voice_settings": {
            "stability": stability,
            "style": style,
        },
    }

    # Speed only supported as a query param (0.7-1.2)
    if speed != 1.0:
        payload["speed"] = round(speed, 2)

    headers = {
        "xi-api-key": settings.elevenlabs_api_key,
        "Content-Type": "application/json",
        "Accept": "audio/mpeg",
    }

    params = {
        "output_format": "mp3_44100_128",
    }

    try:
        async with httpx.AsyncClient(timeout=15.0) as client:
            response = await client.post(
                url, json=payload, headers=headers, params=params
            )
            response.raise_for_status()

            audio_bytes = response.content
            if audio_bytes:
                return audio_bytes

            logger.warning("ElevenLabs returned empty audio")
            return None

    except httpx.HTTPStatusError as e:
        logger.error(
            f"ElevenLabs API error {e.response.status_code}: {e.response.text}"
        )
        return None
    except Exception as e:
        logger.error(f"ElevenLabs TTS error: {e}")
        return None
